### ISSUE TITLE
Failed completing the instance

### ISSUE THREAD

**Issue by bluepilll** [KickVN/SaliensAuto#1]
Im gettings this error in CMD "Failed completing the instance" and my xp isnt going up why? i done all the things correctly like in in instructions https://i.imgur.com/QAKxYgG.png

**Comment by bluepilll** [comment]
ok it seems that is working now im getting xp

**Comment by kandoan** [comment]
Sometimes steam's data is delayed in updating captured status. When that happens it mean the zone is in fact captured but it still shows up as not.
