### ISSUE TITLE
SaliensAuto v1.3.0 URL difference from v1.1.0

### ISSUE THREAD

**Issue by SeasonalFerret** [KickVN/SaliensAuto#2]
v1.3.0: https://github.com/KickVN/SaliensAuto/releases/download/v.1.3.0/SaliensAuto.v1.3.0.zip
v1.1.0: https://github.com/KickVN/SaliensAuto/releases/download/v1.1.0/SaliensAuto.v1.1.0.zip

There's an extra . in the version number.

Nothing important, just broke my auto updater.

**Comment by kandoan** [comment]
My bad. sorry.
