### ISSUE TITLE
Wrong zone and difficulty selection when a new planet arrives and extra planet search

### ISSUE THREAD

**Issue by Mert-Y** [KickVN/SaliensAuto#3]
1. Only easy zones left
2. New planet arrives
3. Scan finds the planets and zones
4. Best planet is selected correctly, which is the new one with the hardzones
5. Best zone selection selects the zone from the old planet which is an easy zone
6. Leaves planet
7. Scans for planets even though we already scanned them before leaving
8. Joins the correct planet
9. Joins the old planet zone which i believe is the new planets zone but it thinks it's the old zone therefore reporting an easy score
10. Scans zones, selects the hard zone and the code continues correctly

> [04:14:53] Checking planets' progress while waiting
> [04:14:54] > Planet ID: 19 - Name: Hexes - Captured rate: 95.68% - Current players: 245,692 - Total players: 1,662,021 - Priority: 19
> [04:14:54] 	Zones: 15 easy, 0 medium, 0 hard, 0 BOSS
> [04:14:54] > Planet ID: 20 - Name: Reboots - Captured rate: 91.72% - Current players: 281,465 - Total players: 1,357,037 - Priority: 20
> [04:14:54] 	Zones: 18 easy, 0 medium, 0 hard, 0 BOSS
> [04:14:55] > Planet ID: 21 - Name: Almost Like A Real Job - Captured rate: 70.62% - Current players: 204,742 - Total players: 1,004,453 - Priority: 21
> [04:14:55] 	Zones: 32 easy, 0 medium, 0 hard, 0 BOSS
> [04:14:55] > Planet ID: 22 - Name: Glory Days I - Captured rate: 74.78% - Current players: 154,727 - Total players: 879,064 - Priority: 22
> [04:14:55] 	Zones: 28 easy, 0 medium, 0 hard, 0 BOSS
> [04:14:56] > Planet ID: 24 - Name: Science! - Captured rate: 99.7% - Current players: 307,272 - Total players: 1,129,477 - Priority: 23
> [04:14:56] 	Zones: 3 easy, 0 medium, 0 hard, 0 BOSS
> [04:14:56] There are only easy zones left. Start searching for highest captured planets.
> [04:14:56] > Planet ID: 19 - Name: Hexes - Captured rate: 95.68% - Current players: 245,694 - Total players: 1,662,021 - Priority: 19
> [04:14:56] > Planet ID: 20 - Name: Reboots - Captured rate: 91.72% - Current players: 281,465 - Total players: 1,357,023 - Priority: 20
> [04:14:56] > Planet ID: 21 - Name: Almost Like A Real Job - Captured rate: 70.62% - Current players: 204,741 - Total players: 1,004,433 - Priority: 21
> [04:14:56] > Planet ID: 22 - Name: Glory Days I - Captured rate: 74.78% - Current players: 154,733 - Total players: 879,056 - Priority: 22
> [04:14:56] > Planet ID: 24 - Name: Science! - Captured rate: 99.7% - Current players: 307,268 - Total players: 1,129,455 - Priority: 23
> .
> .
> .
> [04:22:29] Joining Zone Position: 58 (Row 5, Column 10) - Difficulty: easy - Captured rate: 90.0% - Planet 19
> [04:22:29] Wait 110s to complete the instance
> [04:22:29] Searching for next zone while waiting
> [04:22:30] Next zone is Zone Position: 58 (Row 5, Column 10) - Difficulty: easy - Captured rate: 92.28%
> [04:23:20] Wait 60s
> [04:23:50] Wait 30s
> [04:24:05] Wait 15s
> [04:24:10] Wait 10s
> [04:24:15] Wait 5s
> [04:24:20] Finishing an instance >> Score: 600 - Zone Position: 58 (Row 5, Column 10) - Difficulty: easy - Captured rate: 92.28%
> [04:24:21] Finished. Your progress >> Level: 12 - XP: (4,597,130/4,800,000) - XP Percent: 95.77% - XP Required: 202,870
> [04:24:21] 	Approx time left to reach Level 13: 11h 16m
> [04:24:21] ===================================
> [04:24:21] Joining Zone Position: 58 (Row 5, Column 10) - Difficulty: easy - Captured rate: 94.14% - Planet 19
> [04:24:22] Wait 110s to complete the instance
> [04:24:22] Checking planets' progress while waiting
> [04:24:23] > Planet ID: 19 - Name: Hexes - Captured rate: 96.7% - Current players: 242,683 - Total players: 1,673,531 - Priority: 19
> [04:24:23] 	Zones: 13 easy, 0 medium, 0 hard, 0 BOSS
> [04:24:23] > Planet ID: 20 - Name: Reboots - Captured rate: 92.3% - Current players: 281,726 - Total players: 1,359,380 - Priority: 20
> [04:24:23] 	Zones: 18 easy, 0 medium, 0 hard, 0 BOSS
> [04:24:24] > Planet ID: 21 - Name: Almost Like A Real Job - Captured rate: 71.03% - Current players: 204,716 - Total players: 1,007,096 - Priority: 21
> [04:24:24] 	Zones: 32 easy, 0 medium, 0 hard, 0 BOSS
> [04:24:24] > Planet ID: 22 - Name: Glory Days I - Captured rate: 75.09% - Current players: 154,796 - Total players: 881,246 - Priority: 22
> [04:24:24] 	Zones: 28 easy, 0 medium, 0 hard, 0 BOSS
> [04:24:25] > Planet ID: 25 - Name: Speedrunners Paradise - Captured rate: 0.15% - Current players: 15,567 - Total players: 16,077 - Priority: 24
> [04:24:25] 	Zones: 29 easy, 29 medium, 38 hard, 0 BOSS
> [04:24:25] Searching for next zone while waiting
> [04:24:25] Next planet is Planet 25
> [04:24:25] Next zone is Zone Position: 59 (Row 5, Column 11) - Difficulty: easy - Captured rate: 82.43%
> [04:25:15] Wait 60s
> [04:25:45] Wait 30s
> [04:26:00] Wait 15s
> [04:26:05] Wait 10s
> [04:26:10] Wait 5s
> [04:26:15] Finishing an instance >> Score: 600 - Zone Position: 58 (Row 5, Column 10) - Difficulty: easy - Captured rate: 94.14%
> [04:26:17] Finished. Your progress >> Level: 12 - XP: (4,597,730/4,800,000) - XP Percent: 95.79% - XP Required: 202,270
> [04:26:17] 	Approx time left to reach Level 13: 11h 14m
> [04:26:17] ===================================
> [04:26:17] Attempt to leave previous planet
> [04:26:18] Left planet 19
> [04:26:18] Searching for planet...
> [04:26:18] > Planet ID: 19 - Name: Hexes - Captured rate: 96.75% - Current players: 247,554 - Total players: 1,679,245 - Priority: 19
> [04:26:18] 	Zones: 13 easy, 0 medium, 0 hard, 0 BOSS
> [04:26:18] > Planet ID: 20 - Name: Reboots - Captured rate: 92.34% - Current players: 281,751 - Total players: 1,359,798 - Priority: 20
> [04:26:18] 	Zones: 18 easy, 0 medium, 0 hard, 0 BOSS
> [04:26:19] > Planet ID: 21 - Name: Almost Like A Real Job - Captured rate: 71.08% - Current players: 204,626 - Total players: 1,007,498 - Priority: 21
> [04:26:19] 	Zones: 32 easy, 0 medium, 0 hard, 0 BOSS
> [04:26:19] > Planet ID: 22 - Name: Glory Days I - Captured rate: 75.12% - Current players: 154,741 - Total players: 881,558 - Priority: 22
> [04:26:19] 	Zones: 28 easy, 0 medium, 0 hard, 0 BOSS
> [04:26:19] > Planet ID: 25 - Name: Speedrunners Paradise - Captured rate: 0.33% - Current players: 19,203 - Total players: 20,149 - Priority: 24
> [04:26:19] 	Zones: 29 easy, 29 medium, 38 hard, 0 BOSS
> [04:26:19] => Choose planet 25
> [04:26:19] Attempt to progress in planet 25
> [04:26:20] Joining Zone Position: 59 (Row 5, Column 11) - Difficulty: easy - Captured rate: 82.43% - Planet 25
> [04:26:21] Wait 110s to complete the instance
> [04:26:21] Searching for next zone while waiting
> [04:26:21] Next zone is Zone Position: 8 (Row 1, Column 8) - Difficulty: hard - Captured rate: 6.35%
> [04:27:11] Wait 60s
> [04:27:41] Wait 30s
> [04:27:56] Wait 15s
> [04:28:01] Wait 10s
> [04:28:06] Wait 5s
> [04:28:11] Finishing an instance >> Score: 600 - Zone Position: 59 (Row 5, Column 11) - Difficulty: easy - Captured rate: 82.43%
> [04:28:13] Finished. Your progress >> Level: 12 - XP: (4,598,330/4,800,000) - XP Percent: 95.8% - XP Required: 201,670
> [04:28:13] 	Approx time left to reach Level 13: 11h 12m
> [04:28:13] ===================================
> [04:28:13] Joining Zone Position: 8 (Row 1, Column 8) - Difficulty: hard - Captured rate: 6.35% - Planet 25
> [04:28:13] Wait 110s to complete the instance
> [04:28:13] Searching for next zone while waiting
> [04:28:14] Next zone is Zone Position: 8 (Row 1, Column 8) - Difficulty: hard - Captured rate: 9.8%
> [04:29:04] Wait 60s
> [04:29:34] Wait 30s
> [04:29:49] Wait 15s
> [04:29:54] Wait 10s
> [04:29:59] Wait 5s
> [04:30:04] Finishing an instance >> Score: 2400 - Zone Position: 8 (Row 1, Column 8) - Difficulty: hard - Captured rate: 9.8%
> [04:30:05] Finished. Your progress >> Level: 12 - XP: (4,600,730/4,800,000) - XP Percent: 95.85% - XP Required: 199,270
> [04:30:05] 	Approx time left to reach Level 13: 2h 46m
> [04:30:05] ===================================

**Comment by kandoan** [comment]
I noticed that. Fixed in v1.3.1.
