### ISSUE TITLE
Problems with Heroku

### ISSUE THREAD

**Issue by ojaha065** [KickVN/SaliensAuto#4]
Hi there!

As you might have already heard, Heroku started banning people who were using their service to run Saliens scripts. Apparently, the reason for this is their [TOS](https://www.heroku.com/policy/aup) where is says that all apps that access third-party web content must take effort to

a. identify itself via a unique User Agent string describing the purpose of the web client
b. obey the robots.txt

Modifying the user agent is not a problem, but sadly Steam does have a robots.txt file on https://community.steam-api.com/robots.txt .

Are you planning to do anything about this? My Heroku instance has been fine for days but maybe you should at least add a warning about this to the readme, since according Reddit and Discord many people have gotten their accounts banned over this.

Lastly, I just wanted to thank you for all the work you have put to this. I been running this for five days now and haven't encountered single issue yet. 👍

**Comment by SeasonalFerret** [comment]
Since steam doesn't have a robots.txt, doesn't that mean there are no rules to obey?

**Comment by ojaha065** [comment]
Steam **does** have a robots.txt: https://community.steam-api.com/robots.txt

**Comment by kandoan** [comment]
From what I heard, people were banned by violating [rule 21 of Heroku](https://www.heroku.com/policy/aup). It's a good thing that we haven't got banned yet even though we were just as guilty as them. Why we didn't get banned? I don't know. 

I've changed the User-Agent from v1.4.0 onward to follow their rule. But still, the PHP script had implemented this change too and they still got banned so I'm not really sure about this.

So, I agree that I should warn people about this case.

**Comment by ojaha065** [comment]
Yeah so basically they can suspend every script they want for not obeying Steam's robots.txt...

Maybe they are just being lazy, and they don't actually check what the apps are doing and instead just automatically suspend all instances running certain scripts? Then it would be just natural to SaliensAuto to be unaffected because I don't think so many people are running this on Heroku, so they don't know/care about this one (yet?). I hope we didn't jinx this... :D I also think they are only banning newly created accounts 'cos it would be very unheard-of to just start completely banning people who have been using their services for years. Nevertheless, it's a very bad business practise for them anyway. At least they should clearly communicate what is and isn't allowed.

Just a heads up, you are still using the old user agent on the line 132 of the RequestUtils.java. It does not probably matter tho.

Otherwise, the new version has been running smoothly. We'll see when the next boss shows up. If I catch it live, I will probably pause the script and play it manually for once. If not, I will check the Heroku logs (I'm saving all of them) and let you know if there was any problems.

**Comment by kandoan** [comment]
Oh my bad. I forgot that line. I also think *it probably doesn't matter* . But I'll edit it anyway just to be safe.
And thanks so much for your support. Much appreciated.
