### ISSUE TITLE
Consistently getting a timing error (v 1.4.2)

### ISSUE THREAD

**Issue by manawesome326** [KickVN/SaliensAuto#6]
Every time an instance finishes this error comes up:
`EResult: 93 - Error message: User joined zone 3196 at 1530354224, and now it's 1530354329, which is too soon`
The numbers seem to be unix timestamps and they're always 105s apart, meaning that the thing that happens takes 5 fewer seconds than it should be according to the messages ("wait 110s to complete the instance"). My computer's clock is accurate, so the problem probably isn't on my end.

**Comment by kandoan** [comment]
what about the timestamp that show before every message? is it still 5 fewer seconds between the *wait 110s* line and the *finishing instance* line?
I hardcoded it to wait exactly 110s so that's really strange.

**Comment by manawesome326** [comment]
Er, it turns out I had the process running in two terminal windows at the same time. Closing one window fixed the issue (as you'd expect it to). whoops.
