### ISSUE TITLE
boss Zones not working?

### ISSUE THREAD

**Issue by Bertel4** [KickVN/SaliensAuto#7]
I'm not entirely sure whether boss zones work or not since i intervened and played manually. The feedback in the console made it look like it's not working. http://prntscr.com/k18gxg Here's a screenshot from the console during the boss attack that I took at 20:34 (9 Minutes before the script stopped giving feedback). 

Besides that, thank you for the program, works perfectly!

**Comment by ojaha065** [comment]
For me it got stuck printing "Waiting..." and getting EResult 11 after the the boss was killed. Before that everything worked nicely. After manually restarting everything went back to normal.

**Comment by Bertel4** [comment]
Did you get XP from the script?

**Comment by JulianDavies20** [comment]
For me it also got stuck after the boss was defeated, but I still got the exp.

**Comment by ojaha065** [comment]
I also got the XP. (About 2 million)

**Comment by ojaha065** [comment]
Couple of smaller things I noticed:

1. It would useful to check for BOSS-zones more often because now it didn't pick it up even after finishing normal zone. I had to manually restart. Taking it futher, how about checking every 30 seconds and moving to the BOSS-zone immediately when it arrives. Does the API allow abandoning current zone early?

2. Is it really necessary to spam the console every 5 seconds during boss-battle? I would only print current health/xp every 15 or 20 seconds.

**Comment by Bertel4** [comment]
Okay, I let the script go wild this time and didn't end it despite the
`Waiting . . .`
and
`EResult: 11`.

It worked and I got the points, but the script stopped working after the boss died. So I had to manually restart it after the boss.

**Comment by kandoan** [comment]
Sorry. It's so bad to live in the opposite timezone of US. Bosses always come at midnight here and I was sleeping. So I'm always late to the party.
Although it seems there are a lot of bugs, my heroku is still running fine up till now. Which mean it doesn't stuck forever but only for a while. And I got almost 2 levels so it also means I did get XP from boss. Great!
But bugs are bugs. v1.4.4 would fix those bugs. I has tested through a boss fight so it should work fine. Grab it while you can.

**Comment by ojaha065** [comment]
No need to be sorry, you're awesome keeping these updates coming.

And yes, you seem to be right about it not being stuck forever. I was also sleeping and my instance is still chewing fine.
