### ISSUE TITLE
naming error ?

### ISSUE THREAD

**Issue by SDMU** [KickVN/SaliensAuto#8]
I have downloaded 1.4.7  yet the console says that I'm running 1.4.6 .
![untitled](https://user-images.githubusercontent.com/20798863/42131994-382b9f82-7d2c-11e8-9d8c-c528ffc455ec.png)

**Comment by kandoan** [comment]
fixed in 1.4.8

**Comment by SDMU** [comment]
Ok thank you ! Keep up the hard work !
