### ISSUE TITLE
cannot leave inactive zone

### ISSUE THREAD

**Issue by SDMU** [KickVN/SaliensAuto#9]
![untitled](https://user-images.githubusercontent.com/20798863/42133258-8fa0ca4a-7d44-11e8-98c4-9efacda61d43.png)

**Comment by SDMU** [comment]
I could join another planet after some time/ using other scripts. If this is steam issue please close this issue .

**Comment by kandoan** [comment]
Yes, this is a steam issue. It happens everytime a new planet (or boss sometimes) arrives.
